/**
 * In-memory challenge store for WebAuthn registration and login flows.
 * Challenges are single-use and expire after 5 minutes.
 *
 * NOTE: Anchored to `globalThis` so that the same Map instance is shared
 * across all per-route bundles generated by Turbopack/Webpack in a single
 * Node.js process. Without this, Next.js App Router bundles each route file
 * separately, resulting in separate module instances (and separate Maps) for
 * register-options and register-verify.
 *
 * For multi-process deployments (e.g. Railway with multiple workers), replace
 * this with a shared store such as Redis or a `challenges` SQLite table.
 */

interface ChallengeEntry {
  challenge: string;
  expiresAt: number;
}

type GlobalWithStore = typeof globalThis & {
  _todoAppChallengeStore?: Map<string, ChallengeEntry>;
};

const g = globalThis as GlobalWithStore;
if (!g._todoAppChallengeStore) {
  g._todoAppChallengeStore = new Map<string, ChallengeEntry>();
}
const store = g._todoAppChallengeStore;
const TTL_MS = 5 * 60 * 1000; // 5 minutes

export const challengeStore = {
  save(key: string, challenge: string): void {
    store.set(key, { challenge, expiresAt: Date.now() + TTL_MS });
  },

  /**
   * Retrieves and deletes a challenge (one-time use). Returns null if absent or expired.
   */
  consume(key: string): string | null {
    const entry = store.get(key);
    if (!entry) return null;
    store.delete(key);
    if (Date.now() > entry.expiresAt) return null;
    return entry.challenge;
  },
};
